//Auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const OPEN_REGISTER_MODAL = 'OPEN_REGISTER_MODAL';
export const CLOSE_MODALS = 'CLOSE_MODALS';

//Library fetch
export const FETCH_LIBRARY_START = 'FETCH_LIBRARY_START';
export const FETCH_LIBRARY_SUCCESS = 'FETCH_LIBRARY_SUCCESS';
export const FETCH_LIBRARY_FAIL = 'FETCH_LIBRARY_FAIL';

//Library add
export const ADD_LIBRARY_START = 'ADD_LIBRARY_START';
export const ADD_LIBRARY_SUCCESS = 'ADD_LIBRARY_SUCCESS';
export const ADD_LIBRARY_FAIL = 'ADD_LIBRARY_FAIL';

//Library remove
export const REMOVE_LIBRARY_START = 'REMOVE_LIBRARY_START';
export const REMOVE_LIBRARY_SUCCESS = 'REMOVE_LIBRARY_SUCCESS';
export const REMOVE_LIBRARY_FAIL = 'REMOVE_LIBRARY_FAIL';

//Library clear
export const CLEAR_LIBRARY = 'CLEAR_LIBRARY';

//Messages
export const OPEN_MESSAGE = 'OPEN_MESSAGE';
export const CLOSE_MESSAGE = 'CLOSE_MESSAGE';